// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHzgfXILjrZwRz-OrDVjgiWc3x0NdBMlE',
    appId: '1:502947694320:web:b1c0502798db7a0f2ae435',
    messagingSenderId: '502947694320',
    projectId: 'thermo-ieee-app',
    authDomain: 'thermo-ieee-app.firebaseapp.com',
    storageBucket: 'thermo-ieee-app.appspot.com',
    measurementId: 'G-JHWBB67YE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWDNb6705o2x7bH3Y0PJNtNbdf2TljQsE',
    appId: '1:502947694320:android:5a31d16bbc90784f2ae435',
    messagingSenderId: '502947694320',
    projectId: 'thermo-ieee-app',
    storageBucket: 'thermo-ieee-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnbDDaccL_tDkDUlkdiHqariUc3ez0RaM',
    appId: '1:502947694320:ios:a6481ab66c3662b42ae435',
    messagingSenderId: '502947694320',
    projectId: 'thermo-ieee-app',
    storageBucket: 'thermo-ieee-app.appspot.com',
    iosClientId: '502947694320-pktv8npq5ok7ggn93looal7et27v0884.apps.googleusercontent.com',
    iosBundleId: 'com.example.thermoIeeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnbDDaccL_tDkDUlkdiHqariUc3ez0RaM',
    appId: '1:502947694320:ios:a6481ab66c3662b42ae435',
    messagingSenderId: '502947694320',
    projectId: 'thermo-ieee-app',
    storageBucket: 'thermo-ieee-app.appspot.com',
    iosClientId: '502947694320-pktv8npq5ok7ggn93looal7et27v0884.apps.googleusercontent.com',
    iosBundleId: 'com.example.thermoIeeeApp',
  );
}
